# Generated by Django 4.2.16 on 2024-10-03 08:05

import ckeditor.fields
import cloudinary.models
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("DateAdd", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Admin",
            },
            bases=("travel.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=500)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=1000)),
                ("content", ckeditor.fields.RichTextField()),
                ("active", models.BooleanField(default=True)),
                (
                    "album",
                    models.ForeignKey(
                        default=14,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.album",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
            },
            bases=("travel.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameofhotel", models.CharField(max_length=200)),
                ("address", models.CharField(default="", max_length=1000)),
                ("descriptions", ckeditor.fields.RichTextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Id_Place", models.CharField(max_length=20, unique=True)),
                ("Place_Name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=7000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DepartureTime", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransportCar",
            fields=[
                (
                    "transport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="travel.transport",
                    ),
                ),
                ("seat", models.IntegerField(null=True)),
            ],
            bases=("travel.transport",),
        ),
        migrations.CreateModel(
            name="TransportPLane",
            fields=[
                (
                    "transport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="travel.transport",
                    ),
                ),
                ("TotalSeat", models.IntegerField(null=True)),
                ("EconomySeat", models.IntegerField(null=True)),
                ("BusinessSeat", models.IntegerField(null=True)),
                ("FirstSeat", models.IntegerField(null=True)),
            ],
            bases=("travel.transport",),
        ),
        migrations.AddField(
            model_name="user",
            name="Avatar",
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="Cover",
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sdt",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="vaitro",
            field=models.CharField(
                choices=[("Customer", "Customer"), ("Admin", "Admin")],
                default="Customer",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="OK", max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("Id_Tour", models.CharField(max_length=40, unique=True)),
                ("Tour_Name", models.CharField(max_length=100, unique=True)),
                ("Description", ckeditor.fields.RichTextField()),
                ("DepartureDay", models.DateField()),
                ("Days", models.IntegerField()),
                ("Nights", models.IntegerField()),
                ("Active", models.BooleanField(default=True)),
                ("Adult_price", models.FloatField(default=0)),
                ("Children_price", models.FloatField(default=0)),
                ("cover", cloudinary.models.CloudinaryField(max_length=255, null=True)),
                (
                    "DeparturePlace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Place.Tour_set+",
                        to="travel.place",
                    ),
                ),
                (
                    "DepartureTime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ScheduleTime.Tour_set+",
                        to="travel.scheduletime",
                    ),
                ),
                (
                    "Destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.place"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.album"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.transport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("Name_News", models.CharField(max_length=255, unique=True)),
                (
                    "image_thumbnail",
                    cloudinary.models.CloudinaryField(max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("Content", ckeditor.fields.RichTextField()),
                (
                    "admin",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.admin",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=500)),
                ("Path", cloudinary.models.CloudinaryField(max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "album_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Price", models.FloatField()),
                (
                    "id_hotel",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.hotel",
                    ),
                ),
                (
                    "id_room",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hotel",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Place.Tour_set+",
                to="travel.place",
            ),
        ),
        migrations.CreateModel(
            name="CMT_Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        default="https://cloundinary", max_length=255, null=True
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="travel.tour"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CMT_News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        default="https://cloundinary", max_length=255, null=True
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.news"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CMT_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        default="https://cloundinary", max_length=255, null=True
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="travel.blog"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_booktour", models.CharField(default="", max_length=10)),
                ("book_date", models.DateTimeField(auto_now=True)),
                ("Quantity_Adult", models.IntegerField(default=1)),
                ("Quantity_Children", models.IntegerField(default=0)),
                (
                    "State",
                    models.CharField(
                        choices=[
                            ("Wait for Paid", "Waitforpaid"),
                            ("Paid", "Paid"),
                            ("Complete", "Complete"),
                            ("Reject", "Reject"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "id_customer_bt",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.customer",
                    ),
                ),
                (
                    "id_tour_id",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="travel.tour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("id_bookticket", models.CharField(default="OK", max_length=10)),
                ("OneOrReturn", models.BooleanField(default=True)),
                ("Quantity_Adult", models.IntegerField(default=1)),
                ("Quantity_Children", models.IntegerField(default=0)),
                (
                    "SeatClass",
                    models.CharField(
                        choices=[
                            ("Economy_class", "Economy Class"),
                            ("Business_class", "Business Class"),
                            ("First_class", "First Class"),
                        ],
                        default="Economy_class",
                        max_length=30,
                    ),
                ),
                (
                    "DeparturePlace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Place.Tour_set+",
                        to="travel.place",
                    ),
                ),
                (
                    "DepartureTime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ScheduleTime.Tour_set+",
                        to="travel.scheduletime",
                    ),
                ),
                (
                    "Destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Place.Tour_set+",
                        to="travel.place",
                    ),
                ),
                (
                    "EstimatedTime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ScheduleTime.Tour_set+",
                        to="travel.scheduletime",
                    ),
                ),
                (
                    "user_book",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.transport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("id_book_hotel", models.CharField(default="OK", max_length=10)),
                ("GuestOrSomeone", models.BooleanField(default=True)),
                ("BreakfastOrNone", models.BooleanField(default=True)),
                (
                    "Checkin",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 10, 3, 8, 5, 13, 765602)
                    ),
                ),
                (
                    "Checkout",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 10, 3, 8, 5, 13, 765616)
                    ),
                ),
                ("Quantity_Adult", models.IntegerField(default=1)),
                ("Quantity_Children", models.IntegerField(default=0)),
                (
                    "Room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.hotelroom",
                    ),
                ),
                (
                    "id_hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.hotel"
                    ),
                ),
                (
                    "id_user_book_hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Customer.bookhotel_set+",
                        to="travel.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="travel.tag"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="user_post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="travel.customer",
            ),
        ),
        migrations.CreateModel(
            name="Rating_Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                ("DateUpdate", models.DateTimeField(auto_now=True)),
                ("NumberOfStar", models.IntegerField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="travel.tour"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("tour", "user")},
            },
        ),
        migrations.CreateModel(
            name="Like_Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Active", models.BooleanField(default=False)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.tour"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("tour", "user")},
            },
        ),
        migrations.CreateModel(
            name="Like_News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Active", models.BooleanField(default=False)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="travel.news"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("news", "user")},
            },
        ),
        migrations.CreateModel(
            name="Like_Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Active", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="travel.hotel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("hotel", "user")},
            },
        ),
        migrations.CreateModel(
            name="Like_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Active", models.BooleanField(default=False)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="travel.blog"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("blog", "user")},
            },
        ),
    ]
