# Generated by Django 4.2.16 on 2024-10-03 09:34

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_admin_album_blog_customer_hotel_place_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 9, 34, 1, 744047)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 9, 34, 1, 744071)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="Avatar",
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
