# Generated by Django 4.2.16 on 2024-10-03 12:36

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="album",
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="https://cloundinary", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 12, 35, 47, 43701)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 12, 35, 47, 43717)
            ),
        ),
    ]
