# Generated by Django 4.2.16 on 2024-10-03 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "travel",
            "0004_remove_blog_album_blog_image_alter_bookhotel_checkin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bookhotel",
            name="State",
            field=models.CharField(
                choices=[
                    ("Wait for Paid", "Waitforpaid"),
                    ("Paid", "Paid"),
                    ("Complete", "Complete"),
                    ("Reject", "Reject"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookticket",
            name="State",
            field=models.CharField(
                choices=[
                    ("Wait for Paid", "Waitforpaid"),
                    ("Paid", "Paid"),
                    ("Complete", "Complete"),
                    ("Reject", "Reject"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 13, 16, 33, 741382)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 13, 16, 33, 741398)
            ),
        ),
    ]
