# Generated by Django 4.2.16 on 2024-10-03 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0006_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 15, 9, 37, 44181)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 3, 15, 9, 37, 44196)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="Avatar",
            field=models.CharField(
                default="image/upload/v1727967936/Screenshot_2024-10-03_220517_y6wixr.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="Cover",
            field=models.CharField(
                default="image/upload/v1727922800/mxdjapi8njqincnduxy1.png",
                max_length=255,
                null=True,
            ),
        ),
    ]
