# Generated by Django 4.2.16 on 2024-10-04 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0009_booktour_price_alter_bookhotel_checkin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 7, 38, 56, 484584)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 7, 38, 56, 484597)
            ),
        ),
        migrations.AlterField(
            model_name="booktour",
            name="State",
            field=models.CharField(
                choices=[
                    ("Wait for Paid", "Waitforpaid"),
                    ("Paid", "Paid"),
                    ("Complete", "Complete"),
                    ("Reject", "Reject"),
                ],
                default="Wait for Paid",
                max_length=50,
            ),
        ),
    ]
