# Generated by Django 4.2.16 on 2024-10-04 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0010_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.CharField(
                default="image/upload/v1727967936/Screenshot_2024-10-03_220517_y6wixr.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 12, 49, 58, 374669)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 12, 49, 58, 374692)
            ),
        ),
        migrations.AlterField(
            model_name="cmt_blog",
            name="image",
            field=models.CharField(
                default="image/upload/v1727967936/Screenshot_2024-10-03_220517_y6wixr.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cmt_news",
            name="image",
            field=models.CharField(
                default="image/upload/v1727967936/Screenshot_2024-10-03_220517_y6wixr.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cmt_tour",
            name="image",
            field=models.CharField(
                default="image/upload/v1727967936/Screenshot_2024-10-03_220517_y6wixr.png",
                max_length=255,
                null=True,
            ),
        ),
    ]
