# Generated by Django 4.2.16 on 2024-10-04 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0011_alter_blog_image_alter_bookhotel_checkin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 16, 41, 56, 955662)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 16, 41, 56, 955675)
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image_thumbnail",
            field=models.CharField(
                default="image/upload/v1727922800/mxdjapi8njqincnduxy1.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="cover",
            field=models.CharField(
                default="image/upload/v1727922800/mxdjapi8njqincnduxy1.png",
                max_length=255,
                null=True,
            ),
        ),
    ]
