# Generated by Django 4.2.16 on 2024-10-04 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0013_rename_content_news_content_alter_bookhotel_checkin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="date_post",
            field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 18, 31, 1, 294088)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 4, 18, 31, 1, 294101)
            ),
        ),
    ]
