# Generated by Django 4.2.16 on 2024-10-05 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0014_news_date_post_alter_bookhotel_checkin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 5, 19, 17, 7, 79240)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 5, 19, 17, 7, 79264)
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="date_post",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kdo", models.CharField(default="", max_length=20)),
                ("vdo", models.CharField(default="", max_length=20)),
                ("diadiem", models.CharField(max_length=255, null=True)),
                ("DatePost", models.DateTimeField(auto_now_add=True)),
                (
                    "locationofuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.customer",
                    ),
                ),
            ],
        ),
    ]
