# Generated by Django 4.2.16 on 2024-10-07 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0016_remove_bookticket_departureplace_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketcar",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="ticketplane",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="bookticket",
            name="ticket",
        ),
        migrations.AddField(
            model_name="bookticket",
            name="DeparturePlace",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Place.Tour_set+",
                to="travel.place",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookticket",
            name="DepartureTime",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ScheduleTime.Tour_set+",
                to="travel.scheduletime",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookticket",
            name="Destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Place.Tour_set+",
                to="travel.place",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookticket",
            name="EstimatedTime",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ScheduleTime.Tour_set+",
                to="travel.scheduletime",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookticket",
            name="State",
            field=models.CharField(
                choices=[
                    ("Wait for Paid", "Waitforpaid"),
                    ("Paid", "Paid"),
                    ("Complete", "Complete"),
                    ("Reject", "Reject"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookticket",
            name="vehicle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="travel.transport",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 7, 3, 31, 31, 474173)
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="Checkout",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 7, 3, 31, 31, 474187)
            ),
        ),
        migrations.AlterField(
            model_name="bookticket",
            name="id_bookticket",
            field=models.CharField(default="OK", max_length=10),
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.DeleteModel(
            name="TicketCar",
        ),
        migrations.DeleteModel(
            name="TicketPlane",
        ),
    ]
