# Generated by Django 4.2.16 on 2024-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0021_alter_bookhotel_checkin_alter_bookhotel_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookhotel",
            name="price",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="State",
            field=models.CharField(
                choices=[
                    ("Wait for Paid", "Waitforpaid"),
                    ("Paid", "Paid"),
                    ("Complete", "Complete"),
                    ("Reject", "Reject"),
                ],
                default="Wait for Paid",
                max_length=50,
            ),
        ),
    ]
