# Generated by Django 4.2.16 on 2024-10-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0022_bookhotel_price_alter_bookhotel_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookhotel",
            name="Quantity_Adult",
        ),
        migrations.RemoveField(
            model_name="bookhotel",
            name="Quantity_Children",
        ),
    ]
