# Generated by Django 4.2.16 on 2024-10-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0023_remove_bookhotel_quantity_adult_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="blog",
        ),
        migrations.AddField(
            model_name="blog",
            name="tag",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="travel.tag"
            ),
        ),
    ]
