# Generated by Django 4.2.16 on 2024-10-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0024_remove_tag_blog_blog_tag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating_tour",
            unique_together=set(),
        ),
    ]
