# Generated by Django 4.2.16 on 2024-10-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0025_alter_rating_tour_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating_tour",
            unique_together={("tour", "user")},
        ),
    ]
